spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soloproject
    username: root
    password: 1234

  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ENC(L0SMyiS9QqgWuSakyPSc7J0aM6HezOpYLiwrwmJ6rRav+9WC6sReujEAPST1h3eFqp89YJsmkZ5FSyav/4oXNA==)
  accessExpiration: 3600000
  refreshExpiration: 604800000
  aesKey: ENC(mbqqJa4wFXb8ye5EY5i8Ieizoy/vfRhcmbRtJbe4weQ=)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}


