spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soloproject
    username: root
    password: 1234

  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          kakao-local:
            client-id: ENC(IfaUg+ijVY7LR6660sGPaK8VcIzNVu4XuiiEVhLB8WIHHAvR3gTSra5F5qdt2hPc)
            client-secret: ENC(GF1ntZifRplTlHRwDy4CXMT+61fTI1zQSSQ7d3FggVXdU7mAfpcddiGLzMbjInJC)
            scope:
              - account_email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id

  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ENC(L0SMyiS9QqgWuSakyPSc7J0aM6HezOpYLiwrwmJ6rRav+9WC6sReujEAPST1h3eFqp89YJsmkZ5FSyav/4oXNA==)
  accessExpiration: 3600000
  refreshExpiration: 604800000
  aesKey: ENC(mbqqJa4wFXb8ye5EY5i8Ieizoy/vfRhcmbRtJbe4weQ=)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}


