name : CI

# 워크 플로우가 시작될 브랜치 지정
on:
  push:
    branches: [docker]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 테스트 환경
      - name: Build and Test with Gradle
        run: ./gradlew clean build test